// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models.MainWindow
{
    public partial class CalculatedRoutes
    {
        /// <summary>
        /// Задает уникальный идентификатор записи в базе
        /// </summary>
        [Key]
        [Column("clc_RecordID")]
        public Guid ClcRecordId { get; set; }
        /// <summary>
        /// Хранит идентификатор объекта базы A28
        /// </summary>
        [Column("clc_ObjectID")]
        public int ClcObjectId { get; set; }
        /// <summary>
        /// Время прибытия экипажа до объекта в секундах
        /// </summary>
        [Column("clc_Duration")]
        public double ClcDuration { get; set; }
        /// <summary>
        /// Номер маршрута(экипажа)
        /// </summary>
        [Column("clc_Group")]
        public int ClcGroup { get; set; }
        /// <summary>
        /// Поле для группировки расчётов(объекты из одного расчета имеют один KeyCalc)
        /// </summary>
        [Column("clc_KeyCalcID")]
        public Guid ClcKeyCalcId { get; set; }
        /// <summary>
        /// Наименование расчета для отображения пользователю
        /// </summary>
        [Required]
        [Column("clc_CalcName")]
        public string ClcCalcName { get; set; }
        /// <summary>
        /// Широта (55...)
        /// </summary>
        [Column("clc_GroupLatitude")]
        public double? ClcGroupLatitude { get; set; }
        /// <summary>
        /// Долгота (61...)
        /// </summary>
        [Column("clc_GroupLongitude")]
        public double? ClcGroupLongitude { get; set; }
    }
}