// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models.MainWindow
{
    public partial class UsersReports
    {
        [Key]
        [Column("ID")]
        public Guid Id { get; set; }
        [Required]
        [Column("usr_Login")]
        [StringLength(10)]
        public string UsrLogin { get; set; }
        [Column("rpt_ID")]
        public Guid RptId { get; set; }
    }
}