// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models.GuardObjectsOnMapGBR
{
    public partial class ObjType
    {
        [Key]
        [Column("ObjTypeID")]
        public int ObjTypeId { get; set; }
        public int OrderNumber { get; set; }
        [Required]
        [StringLength(128)]
        public string ObjTypeName { get; set; }
        [StringLength(255)]
        public string Description { get; set; }
        public bool RecordDeleted { get; set; }
        [NotMapped]
        public bool IsShowOnMap { get; set; }
    }
}