// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Keyless]
    [Index(nameof(AccountId), Name = "AccountIdIndex")]
    public partial class AccountExtensionBase
    {
        public Guid AccountId { get; set; }
        [Column("New_bank_name")]
        [StringLength(100)]
        public string NewBankName { get; set; }
        [Column("New_bank_rs")]
        [StringLength(30)]
        public string NewBankRs { get; set; }
        [Column("New_bank_bik")]
        [StringLength(20)]
        public string NewBankBik { get; set; }
        [Column("New_bank_ks")]
        [StringLength(20)]
        public string NewBankKs { get; set; }
        [Column("New_req_inn")]
        [StringLength(12)]
        public string NewReqInn { get; set; }
        [Column("New_req_kpp")]
        [StringLength(9)]
        public string NewReqKpp { get; set; }
        [Column("New_req_status")]
        [StringLength(100)]
        public string NewReqStatus { get; set; }
        [Column("New_req_boss_fio")]
        [StringLength(200)]
        public string NewReqBossFio { get; set; }
        [Column("New_req_buh_fio")]
        [StringLength(100)]
        public string NewReqBuhFio { get; set; }
        [Column("New_req_boss_phone")]
        [StringLength(100)]
        public string NewReqBossPhone { get; set; }
        [Column("New_req_ogrn")]
        [StringLength(30)]
        public string NewReqOgrn { get; set; }
        [Column("New_pass_serial")]
        [StringLength(6)]
        public string NewPassSerial { get; set; }
        [Column("New_pass_number")]
        [StringLength(8)]
        public string NewPassNumber { get; set; }
        [Column("New_pass_issued")]
        [StringLength(100)]
        public string NewPassIssued { get; set; }
        [Column("New_pass_date", TypeName = "datetime")]
        public DateTime? NewPassDate { get; set; }
        [Column("New_partnerId")]
        public Guid? NewPartnerId { get; set; }
        [Column("New_agent_type")]
        public int? NewAgentType { get; set; }
        [Column("New_smallname")]
        [StringLength(100)]
        public string NewSmallname { get; set; }
        [Column("New_1cCode")]
        [StringLength(100)]
        public string New1cCode { get; set; }
        [Column("New_idwww")]
        [StringLength(100)]
        public string NewIdwww { get; set; }
        [Column("New_postmail_index_yur")]
        [StringLength(100)]
        public string NewPostmailIndexYur { get; set; }
        [Column("New_region_yur")]
        [StringLength(100)]
        public string NewRegionYur { get; set; }
        [Column("New_city_yur")]
        [StringLength(100)]
        public string NewCityYur { get; set; }
        [Column("New_postmail_index_transfer")]
        [StringLength(100)]
        public string NewPostmailIndexTransfer { get; set; }
        [Column("New_region_transfer")]
        [StringLength(100)]
        public string NewRegionTransfer { get; set; }
        [Column("New_city_transfer")]
        [StringLength(100)]
        public string NewCityTransfer { get; set; }
        [Column("New_is_export")]
        public bool? NewIsExport { get; set; }
        [Column("New_CrmCode")]
        [StringLength(100)]
        public string NewCrmCode { get; set; }
        [Column("New_phone_for_sms")]
        [StringLength(100)]
        public string NewPhoneForSms { get; set; }
        [Column("New_corp_client")]
        public int? NewCorpClient { get; set; }
        [Column("New_yur_addr_kladr")]
        [StringLength(250)]
        public string NewYurAddrKladr { get; set; }
        [Column("New_fact_addr_kladr")]
        [StringLength(250)]
        public string NewFactAddrKladr { get; set; }
        [Column("New_fact_addr_button")]
        [StringLength(100)]
        public string NewFactAddrButton { get; set; }
        [Column("New_addr_count_kladr")]
        [StringLength(250)]
        public string NewAddrCountKladr { get; set; }
        [Column("New_yur_addr_button")]
        [StringLength(100)]
        public string NewYurAddrButton { get; set; }
        [Column("New_addr_count_button")]
        [StringLength(100)]
        public string NewAddrCountButton { get; set; }
        [Column("New_is_export_button")]
        [StringLength(100)]
        public string NewIsExportButton { get; set; }
        [Column("New_export_all_button")]
        [StringLength(100)]
        public string NewExportAllButton { get; set; }
        [Column("New_fact_addr_uncorrect")]
        public bool? NewFactAddrUncorrect { get; set; }
        [Column("New_yur_addr_uncorrect")]
        public bool? NewYurAddrUncorrect { get; set; }
        [Column("New_transfer_addr_uncorrect")]
        public bool? NewTransferAddrUncorrect { get; set; }
        [Column("New_found")]
        [StringLength(100)]
        public string NewFound { get; set; }
        [Column("New_last_export_date")]
        [StringLength(100)]
        public string NewLastExportDate { get; set; }
        [Column("New_debth_period")]
        public int? NewDebthPeriod { get; set; }
        [Column("New_debth_last_date")]
        [StringLength(100)]
        public string NewDebthLastDate { get; set; }
        [Column("New_shipping")]
        public int? NewShipping { get; set; }
        [Column("New_send_acts")]
        public int? NewSendActs { get; set; }
        [Column("New_poryadok_acts")]
        public int? NewPoryadokActs { get; set; }
        [Column("New_end_date", TypeName = "datetime")]
        public DateTime? NewEndDate { get; set; }
        [Column("New_brand")]
        public Guid? NewBrand { get; set; }
        [Column("New_cat_client")]
        public int? NewCatClient { get; set; }
        [Column("New_cat_corp_client")]
        public int? NewCatCorpClient { get; set; }
        [Column("New_is_vip")]
        public bool? NewIsVip { get; set; }
        [Column("New_history_button")]
        [StringLength(100)]
        public string NewHistoryButton { get; set; }
        [Column("New_debitor_category")]
        public int? NewDebitorCategory { get; set; }
        [Column("New_debitor_first_summ", TypeName = "money")]
        public decimal? NewDebitorFirstSumm { get; set; }
        [Column("new_debitor_first_summ_Base", TypeName = "money")]
        public decimal? NewDebitorFirstSummBase { get; set; }
        [Column("New_debitor_call_date", TypeName = "datetime")]
        public DateTime? NewDebitorCallDate { get; set; }
        [Column("New_debitor_next_call_date", TypeName = "datetime")]
        public DateTime? NewDebitorNextCallDate { get; set; }
        [Column("New_debitor_call_result")]
        public string NewDebitorCallResult { get; set; }
        [Column("New_debitor_last_summ", TypeName = "money")]
        public decimal? NewDebitorLastSumm { get; set; }
        [Column("new_debitor_last_summ_Base", TypeName = "money")]
        public decimal? NewDebitorLastSummBase { get; set; }
        [Column("New_debitor_client_result")]
        public int? NewDebitorClientResult { get; set; }
        [Column("New_debitor_owner")]
        public Guid? NewDebitorOwner { get; set; }

        [ForeignKey(nameof(NewDebitorOwner))]
        public virtual SystemUserBase NewDebitorOwnerNavigation { get; set; }
    }
}