// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Table("AttributePicklistValue", Schema = "MetadataSchema")]
    [Index(nameof(AttributeId), nameof(InProduction), nameof(Value), nameof(CustomizationLevel), Name = "ndx_AttributePicklistValue", IsUnique = true)]
    public partial class AttributePicklistValue
    {
        [Key]
        public Guid AttributePicklistValueId { get; set; }
        public Guid AttributePicklistValueRowId { get; set; }
        public Guid AttributeId { get; set; }
        [Key]
        public bool InProduction { get; set; }
        public int Value { get; set; }
        [Column("State_Status_Value")]
        public int? StateStatusValue { get; set; }
        [StringLength(50)]
        public string InvariantName { get; set; }
        public int? DisplayOrder { get; set; }
        [Required]
        public byte[] VersionNumber { get; set; }
        [Key]
        public byte CustomizationLevel { get; set; }
    }
}