// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Table("Entity", Schema = "MetadataSchema")]
    [Index(nameof(LogicalName), Name = "ndx_entity_logicalname")]
    [Index(nameof(Name), Name = "ndx_entity_name")]
    [Index(nameof(PhysicalName), Name = "ndx_entity_physicalname")]
    public partial class Entity
    {
        [Key]
        public Guid EntityId { get; set; }
        [StringLength(64)]
        public string Name { get; set; }
        public int? ObjectTypeCode { get; set; }
        [StringLength(64)]
        public string PhysicalName { get; set; }
        [StringLength(64)]
        public string LogicalName { get; set; }
        [StringLength(64)]
        public string CollectionName { get; set; }
        [StringLength(64)]
        public string BaseTableName { get; set; }
        [StringLength(64)]
        public string LogicalCollectionName { get; set; }
        public bool IsIntersect { get; set; }
        public bool IsSecurityIntersect { get; set; }
        public int WorkflowEventMask { get; set; }
        public bool IsLookupTable { get; set; }
        public int EventMask { get; set; }
        public bool? IsLogicalEntity { get; set; }
        public bool? IsCustomizable { get; set; }
        public bool? IsCollaboration { get; set; }
        public bool? IsActivity { get; set; }
        [StringLength(64)]
        public string AddressTableName { get; set; }
        public bool? IsMappable { get; set; }
        public int OwnershipTypeMask { get; set; }
        public bool IsAudited { get; set; }
        public bool UsesFullnameConventionRules { get; set; }
        public bool IsParented { get; set; }
        public int? EntityMask { get; set; }
        public bool IsReplicated { get; set; }
        public bool IsReplicationUserFiltered { get; set; }
        public bool IsChildEntity { get; set; }
        public bool IsCustomEntity { get; set; }
        public bool IsActivityParty { get; set; }
        public bool IsValidForAdvancedFind { get; set; }
        [StringLength(64)]
        public string ExtensionTableName { get; set; }
        [Required]
        public byte[] VersionNumber { get; set; }
        [StringLength(64)]
        public string ReportViewName { get; set; }
        public bool IsRequiredOffline { get; set; }
        public bool IsRenameable { get; set; }
        public int DbCascadeMask { get; set; }
        public int HasDeletionStateCode { get; set; }
        [Required]
        [StringLength(255)]
        public string EntityClassName { get; set; }
        [Required]
        [StringLength(255)]
        public string ServiceClassName { get; set; }
        [Required]
        [StringLength(255)]
        public string EntityAssembly { get; set; }
        [Required]
        [StringLength(255)]
        public string ServiceAssembly { get; set; }
        public Guid EntityRowId { get; set; }
        [Key]
        public byte CustomizationLevel { get; set; }
        public bool IsDuplicateCheckSupported { get; set; }
        public bool IsImportable { get; set; }
        public bool IsShareableAcrossOrgs { get; set; }
        public bool IsPublishable { get; set; }
        [StringLength(100)]
        public string OriginalLocalizedName { get; set; }
        [StringLength(100)]
        public string OriginalLocalizedCollectionName { get; set; }
        public bool CanTriggerWorkflow { get; set; }
        public int WorkflowSupport { get; set; }
        public bool CanBeChildInCustomRelationship { get; set; }
        public bool CanBeInCustomEntityAssociation { get; set; }
        public bool CanBeInCustomReflexiveRelationship { get; set; }
        public bool IsMailMergeEnabled { get; set; }
    }
}