// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Table("LocalizedLabel", Schema = "MetadataSchema")]
    [Index(nameof(ObjectId), nameof(InProduction), Name = "ndx_LocalizedLabel_ForPublish")]
    [Index(nameof(InProduction), nameof(ObjectColumnName), nameof(ObjectId), nameof(LanguageId), nameof(CustomizationLevel), Name = "ndx_LocalizedLabel_ForSingleSelect", IsUnique = true)]
    [Index(nameof(InProduction), nameof(ObjectId), nameof(LanguageId), nameof(ObjectColumnName), nameof(CustomizationLevel), Name = "ndx_LocalizedLabel_ForTableJoins", IsUnique = true)]
    public partial class LocalizedLabel
    {
        [Key]
        public Guid LocalizedLabelId { get; set; }
        public Guid LocalizedLabelRowId { get; set; }
        public int LanguageId { get; set; }
        public Guid ObjectId { get; set; }
        [Required]
        [StringLength(128)]
        public string ObjectColumnName { get; set; }
        [Required]
        public string Label { get; set; }
        [Required]
        public byte[] VersionNumber { get; set; }
        [Key]
        public bool? InProduction { get; set; }
        [Key]
        public byte CustomizationLevel { get; set; }
    }
}