// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Table("New_deviceBase")]
    public partial class NewDeviceBase
    {
        public NewDeviceBase()
        {
            NewRentDeviceExtensionBase = new HashSet<NewRentDeviceExtensionBase>();
        }

        [Key]
        [Column("New_deviceId")]
        public Guid NewDeviceId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        public Guid? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }
        public Guid? ModifiedBy { get; set; }
        public Guid? OrganizationId { get; set; }
        [Column("statecode")]
        public int Statecode { get; set; }
        [Column("statuscode")]
        public int? Statuscode { get; set; }
        public int? DeletionStateCode { get; set; }
        public byte[] VersionNumber { get; set; }
        public int? ImportSequenceNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OverriddenCreatedOn { get; set; }
        public int? TimeZoneRuleVersionNumber { get; set; }
        [Column("UTCConversionTimeZoneCode")]
        public int? UtcconversionTimeZoneCode { get; set; }
        public Guid? TransactionCurrencyId { get; set; }
        [Column(TypeName = "decimal(23, 10)")]
        public decimal? ExchangeRate { get; set; }

        [InverseProperty("NewDevice")]
        public virtual NewDeviceExtensionBase NewDeviceExtensionBase { get; set; }
        [InverseProperty("NewDeviceRentDeviceNavigation")]
        public virtual ICollection<NewRentDeviceExtensionBase> NewRentDeviceExtensionBase { get; set; }
    }
}