// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Table("New_deviceExtensionBase")]
    public partial class NewDeviceExtensionBase
    {
        [Key]
        [Column("New_deviceId")]
        public Guid NewDeviceId { get; set; }
        [Column("New_name")]
        [StringLength(200)]
        public string NewName { get; set; }
        [Column("New_price", TypeName = "money")]
        public decimal? NewPrice { get; set; }
        [Column("new_price_Base", TypeName = "money")]
        public decimal? NewPriceBase { get; set; }
        [Column("New_cost", TypeName = "decimal(23, 10)")]
        public decimal? NewCost { get; set; }

        [ForeignKey(nameof(NewDeviceId))]
        [InverseProperty(nameof(NewDeviceBase.NewDeviceExtensionBase))]
        public virtual NewDeviceBase NewDevice { get; set; }
    }
}