// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Keyless]
    [Table("New_servicemanExtensionBase")]
    [Index(nameof(NewServicemanId), Name = "PK_Index", IsUnique = true)]
    public partial class NewServicemanExtensionBase
    {
        [Column("New_servicemanId")]
        public Guid NewServicemanId { get; set; }
        [Column("New_name")]
        [StringLength(100)]
        public string NewName { get; set; }
        [Column("New_phone")]
        [StringLength(50)]
        public string NewPhone { get; set; }
        [Column("New_password")]
        [StringLength(10)]
        public string NewPassword { get; set; }
        [Column("New_dinner")]
        public int? NewDinner { get; set; }
        [Column("New_dinner_new")]
        public bool? NewDinnerNew { get; set; }
        [Column("New_technique_type")]
        public int? NewTechniqueType { get; set; }
        [Column("New_category")]
        public int? NewCategory { get; set; }
        [Column("New_gen_tech")]
        public Guid? NewGenTech { get; set; }
        [Column("New_route1")]
        public int? NewRoute1 { get; set; }
        [Column("New_route2")]
        public int? NewRoute2 { get; set; }
        [Column("New_route3")]
        public int? NewRoute3 { get; set; }
        [Column("New_iswork")]
        public bool? NewIswork { get; set; }

        [ForeignKey(nameof(NewGenTech))]
        public virtual NewServicemanBase NewGenTechNavigation { get; set; }
        [ForeignKey(nameof(NewServicemanId))]
        public virtual NewServicemanBase NewServiceman { get; set; }
    }
}