// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Table("New_servicemanBase")]
    public partial class NewServicemanBase
    {
        public NewServicemanBase()
        {
            NewTest2ExtensionBaseNewNewServicemanPsNavigation = new HashSet<NewTest2ExtensionBase>();
            NewTest2ExtensionBaseNewServicemanServiceorderPsNavigation = new HashSet<NewTest2ExtensionBase>();
            NewTest2ExtensionBaseNewTechniqueEndNavigation = new HashSet<NewTest2ExtensionBase>();
        }

        [Key]
        [Column("New_servicemanId")]
        public Guid NewServicemanId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        public Guid? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }
        public Guid? ModifiedBy { get; set; }
        public Guid? OrganizationId { get; set; }
        [Column("statecode")]
        public int Statecode { get; set; }
        [Column("statuscode")]
        public int? Statuscode { get; set; }
        public int? DeletionStateCode { get; set; }
        public byte[] VersionNumber { get; set; }
        public int? ImportSequenceNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OverriddenCreatedOn { get; set; }
        public int? TimeZoneRuleVersionNumber { get; set; }
        [Column("UTCConversionTimeZoneCode")]
        public int? UtcconversionTimeZoneCode { get; set; }

        [InverseProperty(nameof(NewTest2ExtensionBase.NewNewServicemanPsNavigation))]
        public virtual ICollection<NewTest2ExtensionBase> NewTest2ExtensionBaseNewNewServicemanPsNavigation { get; set; }
        [InverseProperty(nameof(NewTest2ExtensionBase.NewServicemanServiceorderPsNavigation))]
        public virtual ICollection<NewTest2ExtensionBase> NewTest2ExtensionBaseNewServicemanServiceorderPsNavigation { get; set; }
        [InverseProperty(nameof(NewTest2ExtensionBase.NewTechniqueEndNavigation))]
        public virtual ICollection<NewTest2ExtensionBase> NewTest2ExtensionBaseNewTechniqueEndNavigation { get; set; }
    }
}