// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Table("New_test2ExtensionBase")]
    public partial class NewTest2ExtensionBase
    {
        [Key]
        [Column("New_test2Id")]
        public Guid NewTest2Id { get; set; }
        [Column("New_name")]
        [StringLength(200)]
        public string NewName { get; set; }
        [Column("New_address")]
        [StringLength(200)]
        public string NewAddress { get; set; }
        [Column("New_andromeda_serviceorder")]
        public Guid? NewAndromedaServiceorder { get; set; }
        [Column("New_autocreate_ps")]
        public int? NewAutocreatePs { get; set; }
        [Column("New_autotechstr")]
        [StringLength(100)]
        public string NewAutotechstr { get; set; }
        [Column("New_category")]
        public int? NewCategory { get; set; }
        [Column("New_comments")]
        public string NewComments { get; set; }
        [Column("New_contact_info")]
        [StringLength(250)]
        public string NewContactInfo { get; set; }
        [Column("New_date", TypeName = "datetime")]
        public DateTime? NewDate { get; set; }
        [Column("New_datetime_cancredirect")]
        [StringLength(100)]
        public string NewDatetimeCancredirect { get; set; }
        [Column("New_income", TypeName = "datetime")]
        public DateTime? NewIncome { get; set; }
        [Column("New_jobtime")]
        public int? NewJobtime { get; set; }
        [Column("New_moved", TypeName = "datetime")]
        public DateTime? NewMoved { get; set; }
        [Column("New_moved_from")]
        [StringLength(100)]
        public string NewMovedFrom { get; set; }
        [Column("New_new_serviceman_ps")]
        public Guid? NewNewServicemanPs { get; set; }
        [Column("New_number")]
        public int? NewNumber { get; set; }
        [Column("New_obj_name")]
        [StringLength(200)]
        public string NewObjName { get; set; }
        [Column("New_outgone", TypeName = "datetime")]
        public DateTime? NewOutgone { get; set; }
        [Column("New_ps_reglament")]
        public int? NewPsReglament { get; set; }
        [Column("New_result")]
        public int? NewResult { get; set; }
        [Column("New_resultid")]
        public int? NewResultid { get; set; }
        [Column("New_serviceman_serviceorder_ps")]
        public Guid? NewServicemanServiceorderPs { get; set; }
        [Column("New_startdate")]
        [StringLength(100)]
        public string NewStartdate { get; set; }
        [Column("New_techconclusion")]
        public string NewTechconclusion { get; set; }
        [Column("New_technique_end")]
        public Guid? NewTechniqueEnd { get; set; }
        [Column("New_time")]
        [StringLength(30)]
        public string NewTime { get; set; }
        [Column("New_timetransfer")]
        [StringLength(20)]
        public string NewTimetransfer { get; set; }
        [Column("New_transfer_reason")]
        [StringLength(100)]
        public string NewTransferReason { get; set; }
        [Column("New_who_init")]
        [StringLength(100)]
        public string NewWhoInit { get; set; }
        [Column("New_reglament_ps")]
        public int? NewReglamentPs { get; set; }
        [Column("New_route")]
        [StringLength(100)]
        public string NewRoute { get; set; }
        [Column("New_perenos_end")]
        public bool? NewPerenosEnd { get; set; }
        [Column("New_start_reglament_creation")]
        public bool? NewStartReglamentCreation { get; set; }
        [Column("New_add_to_year")]
        [StringLength(100)]
        public string NewAddToYear { get; set; }
        [Column("New_add_to_year_bool")]
        public bool? NewAddToYearBool { get; set; }
        [Column("New_createorders")]
        [StringLength(100)]
        public string NewCreateorders { get; set; }

        [ForeignKey(nameof(NewAndromedaServiceorder))]
        [InverseProperty(nameof(NewAndromedaBase.NewTest2ExtensionBase))]
        public virtual NewAndromedaBase NewAndromedaServiceorderNavigation { get; set; }
        [ForeignKey(nameof(NewNewServicemanPs))]
        [InverseProperty(nameof(NewServicemanBase.NewTest2ExtensionBaseNewNewServicemanPsNavigation))]
        public virtual NewServicemanBase NewNewServicemanPsNavigation { get; set; }
        [ForeignKey(nameof(NewServicemanServiceorderPs))]
        [InverseProperty(nameof(NewServicemanBase.NewTest2ExtensionBaseNewServicemanServiceorderPsNavigation))]
        public virtual NewServicemanBase NewServicemanServiceorderPsNavigation { get; set; }
        [ForeignKey(nameof(NewTechniqueEnd))]
        [InverseProperty(nameof(NewServicemanBase.NewTest2ExtensionBaseNewTechniqueEndNavigation))]
        public virtual NewServicemanBase NewTechniqueEndNavigation { get; set; }
        [ForeignKey(nameof(NewTest2Id))]
        [InverseProperty(nameof(NewTest2Base.NewTest2ExtensionBase))]
        public virtual NewTest2Base NewTest2 { get; set; }
    }
}