// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VityazReports.Models
{
    [Keyless]
    [Index(nameof(SocId), Name = "NonClusteredIndex-20210120-134222", IsUnique = true)]
    public partial class ServiceOrderCoordinates
    {
        [Column("soc_ID")]
        public Guid SocId { get; set; }
        [Column("soc_ServiceOrderID")]
        public Guid SocServiceOrderId { get; set; }
        [Column("soc_IncomeLatitude")]
        [StringLength(50)]
        public string SocIncomeLatitude { get; set; }
        [Column("soc_IncomeLongitude")]
        [StringLength(50)]
        public string SocIncomeLongitude { get; set; }
        [Column("soc_OutcomeLatitide")]
        [StringLength(50)]
        public string SocOutcomeLatitide { get; set; }
        [Column("soc_OutcomeLongitude")]
        [StringLength(50)]
        public string SocOutcomeLongitude { get; set; }
    }
}